### ISSUE TITLE
Not handling errors

### ISSUE THREAD

**Issue by shouston3** [dangerdak/interstellar-soulmates#43]
After configuring the wrong database setup (#34), I've made an invalid request to sign up.

I get a 500 status code page with no logs on the server.

It seems that are swallowing the errors [here](https://github.com/dangerdak/interstellar-soulmates/blob/master/src/model/signUp.js#L9) and then [not doing anything with them](https://github.com/dangerdak/interstellar-soulmates/blob/master/src/model/db/dbConnection.js).

If this happens, it would be good to perhaps log the error [here](https://github.com/dangerdak/interstellar-soulmates/blob/master/src/model/signUp.js#L9) or handle it in the [`dbConnection.js`](https://github.com/dangerdak/interstellar-soulmates/blob/master/src/model/db/dbConnection.js) file

**Comment by dangerdak** [comment]
I'm not sure if this is what you meant, but this shouldn't have been responding with 500 anyway as it wasn't really a server error that was occurring. 

Instead we've changed the status code to 200 and are providing a useful message to the user to let them know that there was an issue with their input - either the passwords don't match or the email already exists in the database.

Thanks for all your excellent issues @shouston3 :smile:

**Comment by shouston3** [comment]
Great, keep logging your errors it in mind for when your on a longer project.

Also if things go wrong on your server it is good to respond with a 400 or 500 error.

If passwords don't match look at responding with a [4** status code](https://stackoverflow.com/questions/32752578/whats-the-appropriate-http-status-code-to-return-if-a-user-tries-logging-in-wit)

Good to know this has been resolved though
