### ISSUE TITLE
Host our database on heroku

### ISSUE THREAD

**Issue by polyccon** [dangerdak/interstellar-soulmates#8]
Once the local database is working we can the proceed to setting up heroku.
The following link may be helpful when setting it up:
[link](https://github.com/foundersandcoders/db-morning-challenge)
and when connecting to it: 
[link](https://www.packtpub.com/mapt/book/web_development/9781782177944/9/ch09lvl1sec77/connecting-to-heroku-postgres-from-psql)

**Comment by dangerdak** [comment]
Done :+1: 
http://interstellar-soulmates.herokuapp.com/
